### ISSUE TITLE
How to use WBF

### ISSUE THREAD

**Issue by Luckycat518** [LeeChanHyuk/Weighted-Boxes-Fusion-implementation#3]
Dear writer，thanks for you great attribution on the implementation of WBF for YOLOV4 and V5. I'm confusing the usage of WBF. Could you please give me a guide?
Q1: What should I do to use WBF? If I want to train model_1 and model_2 in a same dateset and make a combination, what should I do before or after the training to apply the WBF method? 
I have seen that the below command is used for make an assembly, but I don't know how it works. No word like WBF or Ensemble  can be seen.
python test.py --data your_yamlpath.yaml --yolov4_weight v4_best.pt --yolov5_weight v5_best.pt yolov4_cfg yolov4/cfg/yolov4-pacsp-x.cfg
Q2: What is the situation to use WBF? When the backbone of model_1 has been integrated into model_2(for instance, yolo-mobilenet.yaml), can I use the WBF to make an assembly? There is only one model and one result in fact.

**Comment by LeeChanHyuk** [comment]
First, thank you for your issue on my repo.
For Q1: You must change the checkpoint files of model that you want to use and the name of models on my codes.
(Ex, put the two checkpoint files into model/yolov4/weights and model/yolov5 respectively. And change the script like
*python test.py --data your_yamlpath.yaml --yolov4_weight your_first_model_weight.pt --yolov5_weight your_second_model_weight.pt*)
However, I think that the process to change all of the model name in my code is too cumbersome.
**Thus, I will modify my code to make it reusable without unnecessary processes. I think it takes few days.**

For Q2: You can use wbf to combine the prediction results of two models to improve generalization performance.
Thus, I think there is no special advantage if you use model_1 integrated into model_2.

**Comment by LeeChanHyuk** [comment]
I've made my code usable through your new model with just a few tweaks.
If you want to use my code with your new models, you must modify the configuration.yaml in ROOT folder with your own path and run the test.py in ROOT folder.
(The detailed instruction is in the readme.md)
If there is still a limitation to using my code, please leave me a comment about your detailed situation.
Thank you.

**Comment by Luckycat518** [comment]
> First, thank you for your issue on my repo. For Q1: You must change the checkpoint files of model that you want to use and the name of models on my codes. (Ex, put the two checkpoint files into model/yolov4/weights and model/yolov5 respectively. And change the script like _python test.py --data your_yamlpath.yaml --yolov4_weight your_first_model_weight.pt --yolov5_weight your_second_model_weight.pt_) However, I think that the process to change all of the model name in my code is too cumbersome. **Thus, I will modify my code to make it reusable without unnecessary processes. I think it takes few days.**
> 
> For Q2: You can use wbf to combine the prediction results of two models to improve generalization performance. Thus, I think there is no special advantage if you use model_1 integrated into model_2.

Okay，thanks for your kind reply.

**Comment by LeeChanHyuk** [comment]
Thank you. If you have another question on my repo, please make another issue.
